[package]
name = "radical-headless"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.2", features = ["postgres"] }
rocket = "0.5.0-rc.2"
dotenvy = "0.15"